export const SET_FOOD_LOADING = "SET_FOOD_LOADING";

export const GET_FOOD_ITEMS = "GET_FOOD_IETMS";
export const GET_FOOD_ITEMS_SUCCESS = "GET_FOOD_IETMS_SUCCESS";
export const GET_FOOD_ITEMS_FAIL = "GET_FOOD_IETMS_FAIL";
